### ISSUE TITLE
Personalizar Template

### ISSUE THREAD

**Issue by NoMolestar** [NoMolestar/Camera-based-Water-Stage-and-Discharge-Prediction-with-Machine-Learning#1]

**Comment by NoMolestar** [comment]
Lunes 10 Octubre 2022

**Comment by Javierleal-debug** [comment]
El documento estaba listo desde ayer, a lo largo de la semana trabajaré en actualizarlo
[Caudales.pdf](https://github.com/NoMolestar/Camera-based-Water-Stage-and-Discharge-Prediction-with-Machine-Learning/files/9759399/Caudales.pdf)
